### PR TITLE
[DEC-1056] Updated ssh-run-ecs-task readme to specify that JSON 11 is not supported

### PR DESCRIPTION
**Pull request by dlm6693**

### CODE REVIEW

**Review by matthewcburke — APPROVED** [review]
Thanks for updating this!

The extra commits were because the base branch was `master`. We've switched to using `main` as the primary/production branch for (hopefully) all repos. I updated the base branch on this PR.

**Comment by matthewcburke** [comment]
@dlm6693 would you create a JIRA ticket for this? Can be bare bones, but we should create a ticket and reference the ticket in the commit message.

**Comment by dlm6693** [comment]
@matthewcburke I did already: https://decile.atlassian.net/browse/DEC-1033

Did you want me to make one just for updating the readme as well?

**Comment by matthewcburke** [comment]
> @matthewcburke I did already: https://decile.atlassian.net/browse/DEC-1033
> 
> Did you want me to make one just for updating the readme as well?

Yes, that's what I was saying. At some point in the past, it was very important to our QA team that every commit had an associated JIRA number, so I've gotten in the habit of it. Maybe that habit is outdated, but I thought that this was also part of our secure coding guidelines and part of SOC2 compliance. Does it not ring a bell from your recent onboarding?

Also when you merge a feature PR to `develop`, `release` or `main` would you use the "Squash and Merge" feature of the GitHub UI? That way we don't pollute our commit history with a bunch of unnecessary merge commits. When we merge one of those three main branches into another, we use merge commits so as not to change the commit history. Let me know if this isn't clear, and I can show you what I mean or explain in more detail.

Thanks

**Comment by dlm6693** [comment]
@dlm6693 truthfully no that doesn't ring a bell! And sorry about clicking the wrong button for merging. I'll be sure to do squash and merge in the future to not create merge commits. I just created a jira ticket and will be updating this pr accordingly.

**Comment by matthewcburke** [comment]
no worries, just trying to communicate expectations early and often. Not a big deal in this case.

**Pull request merged**
